# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import board_pb2 as board__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in board_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BoardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostMessage = channel.unary_unary(
                '/board.BoardService/PostMessage',
                request_serializer=board__pb2.PostMessageRequest.SerializeToString,
                response_deserializer=board__pb2.PostMessageResponse.FromString,
                _registered_method=True)
        self.PollMessage = channel.unary_unary(
                '/board.BoardService/PollMessage',
                request_serializer=board__pb2.PollMessageRequest.SerializeToString,
                response_deserializer=board__pb2.PollMessageResponse.FromString,
                _registered_method=True)
        self.PollPool = channel.unary_unary(
                '/board.BoardService/PollPool',
                request_serializer=board__pb2.PollPoolRequest.SerializeToString,
                response_deserializer=board__pb2.PollPoolResponse.FromString,
                _registered_method=True)
        self.AckMessage = channel.unary_unary(
                '/board.BoardService/AckMessage',
                request_serializer=board__pb2.AckMessageRequest.SerializeToString,
                response_deserializer=board__pb2.AckMessageResponse.FromString,
                _registered_method=True)


class BoardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMessage,
                    request_deserializer=board__pb2.PostMessageRequest.FromString,
                    response_serializer=board__pb2.PostMessageResponse.SerializeToString,
            ),
            'PollMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PollMessage,
                    request_deserializer=board__pb2.PollMessageRequest.FromString,
                    response_serializer=board__pb2.PollMessageResponse.SerializeToString,
            ),
            'PollPool': grpc.unary_unary_rpc_method_handler(
                    servicer.PollPool,
                    request_deserializer=board__pb2.PollPoolRequest.FromString,
                    response_serializer=board__pb2.PollPoolResponse.SerializeToString,
            ),
            'AckMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMessage,
                    request_deserializer=board__pb2.AckMessageRequest.FromString,
                    response_serializer=board__pb2.AckMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'board.BoardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('board.BoardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BoardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BoardService/PostMessage',
            board__pb2.PostMessageRequest.SerializeToString,
            board__pb2.PostMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BoardService/PollMessage',
            board__pb2.PollMessageRequest.SerializeToString,
            board__pb2.PollMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BoardService/PollPool',
            board__pb2.PollPoolRequest.SerializeToString,
            board__pb2.PollPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BoardService/AckMessage',
            board__pb2.AckMessageRequest.SerializeToString,
            board__pb2.AckMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BucketBoardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBucket = channel.unary_unary(
                '/board.BucketBoard/CreateBucket',
                request_serializer=board__pb2.CreateBucketRequest.SerializeToString,
                response_deserializer=board__pb2.CreateBucketResponse.FromString,
                _registered_method=True)
        self.PollBuckets = channel.unary_unary(
                '/board.BucketBoard/PollBuckets',
                request_serializer=board__pb2.PollBucketsRequest.SerializeToString,
                response_deserializer=board__pb2.PollBucketsResponse.FromString,
                _registered_method=True)
        self.UpdateBucket = channel.unary_unary(
                '/board.BucketBoard/UpdateBucket',
                request_serializer=board__pb2.UpdateBucketRequest.SerializeToString,
                response_deserializer=board__pb2.UpdateBucketResponse.FromString,
                _registered_method=True)
        self.AckBucket = channel.unary_unary(
                '/board.BucketBoard/AckBucket',
                request_serializer=board__pb2.AckBucketRequest.SerializeToString,
                response_deserializer=board__pb2.AckBucketResponse.FromString,
                _registered_method=True)


class BucketBoardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BucketBoardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBucket,
                    request_deserializer=board__pb2.CreateBucketRequest.FromString,
                    response_serializer=board__pb2.CreateBucketResponse.SerializeToString,
            ),
            'PollBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.PollBuckets,
                    request_deserializer=board__pb2.PollBucketsRequest.FromString,
                    response_serializer=board__pb2.PollBucketsResponse.SerializeToString,
            ),
            'UpdateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBucket,
                    request_deserializer=board__pb2.UpdateBucketRequest.FromString,
                    response_serializer=board__pb2.UpdateBucketResponse.SerializeToString,
            ),
            'AckBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.AckBucket,
                    request_deserializer=board__pb2.AckBucketRequest.FromString,
                    response_serializer=board__pb2.AckBucketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'board.BucketBoard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('board.BucketBoard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BucketBoard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BucketBoard/CreateBucket',
            board__pb2.CreateBucketRequest.SerializeToString,
            board__pb2.CreateBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BucketBoard/PollBuckets',
            board__pb2.PollBucketsRequest.SerializeToString,
            board__pb2.PollBucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BucketBoard/UpdateBucket',
            board__pb2.UpdateBucketRequest.SerializeToString,
            board__pb2.UpdateBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/board.BucketBoard/AckBucket',
            board__pb2.AckBucketRequest.SerializeToString,
            board__pb2.AckBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
