run:
  base_dir: "runs"
  name: null          # or "board_crypto_experiment"

general:
  epochs: 2
  batch_size: 128
  lr: 0.001
  suppress_warnings: true
  log_level: "INFO"

  # verbosity
  m2_verbose: true
  m2_log_every: 50

  m1m3_verbose: true
  m1m3_log_every: 50

  board_verbose: true
  board_log_every: 100

peers:
  M2:
    - name: "m2_a"
      key: "secret_a"
    - name: "m2_b"
      key: "secret_b"

  M1M3:
    - name: "client_1"
      target_m2: "m2_a"
    - name: "client_2"
      target_m2: "m2_a"
    - name: "client_3"
      target_m2: "m2_b"
