run:
  base_dir: "runs"
  name: null          # or "my_experiment_01"

general:
  epochs: 3
  batch_size: 128
  lr: 0.001
  suppress_warnings: true   # hide Ray noise
  log_level: "INFO"
  
  m2_verbose: true      # if true, M2 logs every few fwd/bwd calls
  m2_log_every: 50      # log every N forward/backward operations

peers:
  M2:
    - name: "m2_a"
    - name: "m2_b"

  M1M3:
    - name: "client_1"
      target_m2: "m2_a"
    - name: "client_2"
      target_m2: "m2_a"
    - name: "client_3"
      target_m2: "m2_b"
